services:
  ms-discovery:
    build: ./ms-discovery
    container_name: discovery-doc
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s   # permet à Eureka de démarrer avant le 1er test
  ms-config:
    build: ./ms-config
    container_name: config-doc
    ports:
      - "9999:9999"
    environment:
      - DISCOVERY_URL=http://discovery-doc:8761/eureka
    depends_on:
      ms-discovery:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9999/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  equipement-service:
    build: ./equipement-service
    container_name: equipement-doc
    ports:
      - "1471:1471"
    environment:
      - DISCOVERY_URL=http://discovery-doc:8761/eureka
      - CONFIG_URL=http://config-doc:9999
    depends_on:
      ms-config:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8084/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  client-service:
    build: ./client-service
    container_name: client-doc
    ports:
      - "1472:1472"
    environment:
      - DISCOVERY_URL=http://discovery-doc:8761/eureka
      - CONFIG_URL=http://config-doc:9999
    depends_on:
      ms-config:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8083/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  location-service:
    build: ./location-service
    container_name: location-doc
    ports:
      - "1473:1473"
    environment:
      - DISCOVERY_URL=http://discovery-doc:8761/eureka
      - CONFIG_URL=http://config-doc:9999
    depends_on:
      ms-config:
        condition: service_healthy
      equipement-service:
        condition: service_healthy
      client-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  api-gateway:
    build: ./api-gateway
    container_name: gateway-doc
    ports:
      - "8888:8888"
    environment:
      - DISCOVERY_URL=http://discovery-doc:8761/eureka
    depends_on:
      location-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
